In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np

dataset = pd.read_csv(r"diabetes.csv")
print(len(dataset))
dataset.columns



768


Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [3]:
zero_not_accepted = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

for column in zero_not_accepted:
    dataset[column] = dataset[column].replace(0, np.NaN)
    mean = int(dataset[column].mean(skipna=True))
    dataset[column] = dataset[column].replace(np.NaN, mean)

In [4]:
X = dataset.drop(['Outcome'], axis=1)
y = dataset.Outcome

X_train, X_test, y_train, y_test = train_test_split(X, y,  test_size=0.1, random_state=0)

In [14]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)





In [48]:
# first we try our model for 11 nieghbours
classifier = KNeighborsClassifier(n_neighbors=11)

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
y_pred


array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0], dtype=int64)

In [49]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[44  7]
 [ 6 20]]


In [50]:
print(accuracy_score(y_test, y_pred))

0.8311688311688312


In [18]:
#now we are going to try the model for 8 neighbours
classifier = KNeighborsClassifier(n_neighbors=8)

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
y_pred


array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0], dtype=int64)

In [19]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[45  6]
 [ 9 17]]


In [20]:
print(accuracy_score(y_test, y_pred))

0.8051948051948052


In [51]:
#now we are going to try the model for 9 neighbours
classifier = KNeighborsClassifier(n_neighbors=9)

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
y_pred


array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0], dtype=int64)

In [52]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[44  7]
 [ 6 20]]


In [53]:
print(accuracy_score(y_test, y_pred))

0.8311688311688312
